services:
  redis:
    image: redis
    command: redis-server --save 60 1 --loglevel warning --requirepass $REDIS_AUTH
    environment:
      - REDIS_AUTH=${REDIS_AUTH}
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
    volumes:
      - data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  redisinsight:
    image: redislabs/redisinsight
    ports:
      - 5540:5540
    volumes:
      - redisinsight_data:/db
    depends_on:
      - redis
 
volumes:
  data:
  redisinsight_data:
 
networks:
  default:
    name: redis_network
 